name: Code Checks

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform in Module
        run: terraform init
        working-directory: module/aws_sentiments

      - name: Format Check in Module
        run: terraform fmt -check
        working-directory: module/aws_sentiments

      - name: Validate Terraform in Module
        run: terraform validate
        working-directory: module/aws_sentiments

      - name: Initialize Terraform in infrastructure
        run: terraform init
        working-directory: infrastructure

      - name: Format Check in infrastructure
        run: terraform fmt -check
        working-directory: infrastructure

      - name: Validate Terraform in infrastructure
        run: terraform validate
        working-directory: infrastructure        

  lint-python:
    name: Python Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Flake8
        run: pip install flake8

      - name: Run Python Linting
        run: flake8 lambda_function/ --count --show-source --statistics
